version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "02:00"
  open-pull-requests-limit: 99
  ignore:
    - dependency-name: "spring-framework-bom"
      update-types: ["version-update:semver-major"]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "02:00"
  open-pull-requests-limit: 99
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "02:00"
  open-pull-requests-limit: 99
