version: 2
registries:
  maven-artifactory:
    # Actually it's not needed to be accessed, but Dependabot strats search from this repo
    type: maven-repository
    url: https://maven.pkg.github.com/vividus-framework/vividus
    username: token
    password: ${{secrets.TOKEN_FOR_VIVIDUS_PACKAGE_REGISTRY}}
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "02:00"
  open-pull-requests-limit: 99
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "02:00"
  open-pull-requests-limit: 99
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "02:00"
  open-pull-requests-limit: 99
